### ISSUE TITLE
Create "intronic space" parameter

### ISSUE THREAD

**Issue by upendrak** [Evolinc/Evolinc-II#4]
Allow for variable distance for removing gaps and merging hits on similar scaffolds (max gap length currently set to length of query lncRNA).

**Comment by andrew-d-l-nelson** [comment]
We believe that this has been addressed through the incorporation of the slice-aware aligner, minimap2 as the similarity search algorithm instead of straight up BLASTn. As such, this issue will be resolved in the next update of Evolinc-II
